version: '3.8'

services:
  streamlit_app:
    image: diagnostic:0.0.2
    restart: always
    networks:
      - diagnostic-network

  nginx:
    image: nginx:1.27.0
    restart: always
    ports:
      - "80:80"
    volumes:
      - /home/yechank/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - diagnostic-network

networks:
  diagnostic-network:
    driver: bridge
